# Generated by Django 6.0.5 on 2026-05-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('antibiotik', 'Antibiotik'), ('analgesik', 'Analgesik'), ('vitamin', 'Vitamin'), ('antasida', 'Antasida'), ('lainnya', 'Lainnya')], max_length=20)),
                ('unit', models.CharField(choices=[('tablet', 'Tablet'), ('kapsul', 'Kapsul'), ('sirup', 'Sirup'), ('salep', 'Salep'), ('injeksi', 'Injeksi')], max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
