# Generated by Django 6.0.5 on 2026-05-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='brith_date',
            new_name='birth_date',
        ),
    ]
